DROP TABLE IF EXISTS users;
DROP EXTENSION IF EXISTS "uuid-ossp";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  email TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  surname TEXT NOT NULL,
  address TEXT NOT NULL,
  username TEXT UNIQUE NOT NULL,
  profile_pic TEXT,
  bio TEXT,
  hash TEXT NOT NULL,
  token TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
  updated_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'UTC')
)